### ISSUE TITLE
Rename some ADTS

### ISSUE THREAD

**Issue by baetheus** [baetheus/fun#167]
Following gcanti's work in fp-ts hkt 3.0.0, rename the following:

1. Task => Async
2. IO => Sync
3. TaskEither => AsyncEither
4. IOEither => SyncEither
5. Guard = Refinement

**Comment by baoshan** [comment]
May I know the proper way to port some of my existing code leveraging `Array.traverse` and `Task.Applicative` (or `ApplicativeSeq`) such as:

```
Array.traverse(Task.Applicative)(fetch)(ids)
```

Thanks and sorry for interrupting your mind flow.

**Comment by pixeleet** [comment]
Great question @baoshan, yesterday I was updating to the latest version of `fun` and noticed that Monad's are now separated into Seq/Par (because of ap being seq/par) and so I think it would be
```ts
array.traverse(MonadTaskSequential)((x: number) => () => Promise.resolve(x * 2))([1, 2, 3]);
```

@baetheus also noticed that Do/bind is not exposed anymore. I remember there was a reason but can't recall atm.
